### ISSUE TITLE
rake doesn't work

### ISSUE THREAD

**Issue by ryanbooker** [schacon/ticgit#1]
(in /usr/local/src/ticgit)
rake aborted!
undefined method `manage_gems' for Gem:Module
/usr/local/src/ticgit/Rakefile:2
(See full trace by running task with --trace)

**Comment by ryanbooker** [comment]
Removing Gem::manage_gems from the rake file seemed to work.

**Comment by davidlee** [comment]
yep, same here. thanks

**Comment by todd-a-jacobs** [comment]
Patched by issue #10.

**Comment by todd-a-jacobs** [comment]
Include lib/ticgit/command/ in gem files list.
- Closed by a76e06d42fc852ce3e319974e7a280fda4de63a3.
- Moved gemspec into Rakefile to take advantage of Rake&#39;s FileList
  globbing.
- Removed ticgit.gemspec, as its contents are now in the Rakefile.
