### ISSUE TITLE
ticgit repo branch should be created on `ti init` not `ti`

### ISSUE THREAD

**Issue by blindgaenger** [schacon/ticgit#3]
Nobody (including me) expects a new branch to be created by simply typing `ti`. The standard is to use an `init` command. A very wide-spread convention in the ruby/git community. So it would be better to show some little hint or the command list instead.

**Comment by jeffWelling** [comment]
Copied this issue to the proper TicGit-ng issue tracker.
https://github.com/jeffWelling/ticgit/issues
Closing this issue.
