### ISSUE TITLE
LoadError `gem_original_require` no such file to load -- git

### ISSUE THREAD

**Issue by wrboyce** [schacon/ticgit#5]
Apologies in advance, I'm not a Ruby developer so know very little of Gems (and was under the impression `gem` handles dependencies, perhaps this assumption is the issue)..

I followed the instruction on the Wiki for installation:
    $ sudo gem install schacon-ticgit --source=http://gems.github.com
    Successfully installed schacon-ticgit-0.3.6
    1 gem installed

But when I try to use `ti`:
    $ ti
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- git (LoadError)
            from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
            from /Library/Ruby/Gems/1.8/gems/schacon-ticgit-0.3.6/lib/ticgit.rb:8
            from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
            from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
            from /Library/Ruby/Gems/1.8/gems/schacon-ticgit-0.3.6/bin/ti:9
            from /usr/bin/ti:19:in `load'
            from /usr/bin/ti:19

I am running Mac OS X 10.6 Snow Leopard:
    $ uname -a
    Darwin anarki.local 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386

With RubyGem version 1.3.1:
    $ gem --version
    1.3.1

And Ruby version 1.8.7:
    $ ruby --version
    ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]

**Comment by wrboyce** [comment]
I appear to have resolved this by installing the 'git' gem.

Should 'git' be listed as a dependency?

**Comment by todd-a-jacobs** [comment]
Yes, it should. There seems to be some discrepancies between the gem spec in the source tree and the version currently up on rubygems.org, so I'm looking into it. Patching in the proper dependency should be easy once the canonical source for the gem is identified.

**Comment by jeffWelling** [comment]
The git gem is now listed as a dependency in the documentation and the gemspec.
For reference, in the future we plan to switch to the Rugged gem.
Closing this issue.
