### ISSUE TITLE
Feature: braking down ticket into smaller tasks

### ISSUE THREAD

**Issue by placek** [schacon/ticgit#8]
Hi,
for bug reports / issue tracking I am using Pivotal Tracker (www.pivotaltracker.com). They have fantastic feature: tasks. Tasks are (optional) parts of ticket that we can check/uncheck. It's a good form of describing issue and to track the workflow.

**Comment by todd-a-jacobs** [comment]
How would you see that working in the ticgit model?  Fundamentally, tickets are a group of files in a branch directory. How would you go about breaking them into tasks?

**Comment by placek** [comment]
For example there will be four commands:<br/>
- ti task add <description> [<issue_number>] - add task<br/>
- ti task remove <task_number> [<issue_number>] - remove task<br/>
- ti task tick <task_number> [<issue_number>] - mark task as done<br/>
- ti task untick <task_number> [<issue_number>] - mark task as undone<br/>

Task can be a file like comment is. In task file there will be description and state (or if you wish it could be in different files). Every task will have an id, so during work you can precisely say what task you have working on.

**Comment by jeffWelling** [comment]
I like this idea.  I'm going to leave it open to remind myself to add it to my TODO file.
